# -*- coding: utf-8 -*-
"""huggingfacespeechtotext.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/Jayshree88patra/30d5b04c4a8628485d5461b468cca418/huggingfacespeechtotext.ipynb
"""

pip install transformers

from transformers import pipeline

import transformers
print(transformers.__version__)

import librosa
import torch
import IPython.display as display
# fine tune
from transformers import Wav2Vec2ForCTC, AutoProcessor
import numpy as np

processor = AutoProcessor.from_pretrained("facebook/wav2vec2-base-960h")
model = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")

"""Once your audio file is uploaded (e.g., named `audio.wav` and located in `/content/`), you can load and process it using the following steps:"""

# Define the path to your uploaded audio file
AUDIO_FILE_PATH = "/content/harvard.wav" # Updated to use the provided file

# Load the audio file
# Wav2Vec2 models typically expect a sample rate of 16kHz
try:
    speech, rate = librosa.load(AUDIO_FILE_PATH, sr=16000)
    print(f"Audio loaded: Sample rate = {rate} Hz, Duration = {len(speech)/rate:.2f} seconds")

    # Display the audio (optional)
    display.Audio(speech, rate=rate)

except FileNotFoundError:
    print(f"Error: Audio file not found at {AUDIO_FILE_PATH}. Please ensure it is uploaded correctly.")
except Exception as e:
    print(f"An error occurred while loading the audio file: {e}")

"""Now, let's tokenize the audio and pass it through the model to get predictions."""

# Tokenize the input speech using the processor
input_values = processor(speech, sampling_rate=rate, return_tensors="pt").input_values

# Get logits from the model
with torch.no_grad():
    logits = model(input_values).logits

# Take argmax to get the predicted token IDs
predicted_ids = torch.argmax(logits, dim=-1)

# Decode the predicted IDs to text using the processor
transcription = processor.batch_decode(predicted_ids)

print("Transcription:")
print(transcription[0])

"""## Uploading Your Project to GitHub

Follow these steps to upload your project files to a GitHub repository from Colab.

### Step 1: Configure Git User Credentials (if not already done)

Replace `"YOUR_GITHUB_USERNAME"` and `"YOUR_EMAIL"` with your actual GitHub username and the email associated with your GitHub account.
"""

!git config --global user.name "YOUR_GITHUB_USERNAME"
!git config --global user.email "YOUR_EMAIL"

print("Git credentials configured.")

"""### Step 2: Clone your GitHub Repository

Replace `"YOUR_REPOSITORY_URL"` with the HTTPS clone URL of your GitHub repository (e.g., `https://github.com/your_username/your_repo.git`). This will create a local copy of your repository in the Colab environment.

### Troubleshooting: Clear existing repository directory

If you encounter an error like `fatal: destination path 'your_repo_name' already exists`, run the cell below to remove the existing directory before re-attempting to clone the repository.
"""

!rm -rf /content/speech-to-text-
print("Existing repository directory removed.")

# Commented out IPython magic to ensure Python compatibility.
# Clone your repository
# IMPORTANT: Replace "YOUR_REPOSITORY_URL" with the actual HTTPS clone URL of your GitHub repository.
!git clone "https://github.com/Jayshree88patra/speech-to-text-.git"

# Change to the repository directory.
# IMPORTANT: Replace 'your_repo_name' with the actual name of the folder created by the git clone command.
# This name usually matches your repository's name (e.g., if URL is https://github.com/user/my_project.git, the folder is 'my_project').
# %cd /content/speech-to-text-

print("Repository cloned and current directory changed.")

"""### Step 3: Move Project Files (including `harvard.wav`) into your Repository

This command moves the `harvard.wav` file from `/content/` to your cloned repository directory. If you have other project files (e.g., other data, a saved version of this notebook) that you want to include, you will need to move them into this directory as well using similar `!mv` commands or by manually downloading and moving them if they are the notebook itself.
"""

# Move the audio file into the cloned repository's current directory
!mv /content/harvard.wav .

# If you saved your current notebook file (e.g., 'my_notebook.ipynb') and want to include it,
# you would need to move it similarly. For example:
# !mv "/content/drive/MyDrive/Colab Notebooks/my_notebook.ipynb" .

print("Audio file and other specified files moved to repository.")

"""### Step 4: Add, Commit, and Push Changes to GitHub

This is where you'll stage your file, create a commit, and push it to your remote GitHub repository. You may be prompted for your GitHub username and Personal Access Token (PAT) here.

**Note**: GitHub no longer supports password authentication for Git operations. You must use a [Personal Access Token (PAT)](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) instead of your password. When prompted for a password, enter your PAT.
"""

# Add all new and modified files in the current directory to your Git staging area
!git add .

# Commit the changes with a descriptive message
!git commit -m "Upload project files including harvard.wav"

# Push the changes to your GitHub repository
!git push origin main # Or 'master', depending on your repository's default branch name

print("Changes pushed to GitHub.")